# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "data-dojo"
client_id = "af08e456d530202e9548ebdf97bd3da3"
application_url = "https://o-grade-constant-short.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://o-grade-constant-short.trycloudflare.com/auth/callback",
  "https://o-grade-constant-short.trycloudflare.com/auth/shopify/callback",
  "https://o-grade-constant-short.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6e47eab7.myshopify.com"
